name: Publish Docker
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    name: Publish Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout twilio-php
        uses: actions/checkout@v2

      - name: Set tag
        run: echo "GITHUB_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set hash
        run: echo "API_DEFINITIONS_SHA=git log --oneline | grep Regenerated | head -n1 | cut -d ' ' -f 5" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push image
        run: echo $GITHUB_TAG && make testme && make docker-build docker-push
