name: Publish Docker
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    name: Publish Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout twilio-php
        uses: actions/checkout@v2

#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_AUTH_TOKEN }}

      - name: Test tags
        env:
          GITHUB_TAG: ${{ env.GITHUB_TAG }}
        run: echo $GITHUB_TAG
